### ISSUE TITLE
Help !!

### ISSUE THREAD

**Issue by labviewegypt** [danchitnis/FPGA-text-overlay#1]
First of all ,thank you for sharing your FPGA Text Overlay project on Github.
I have a similar project like this and I am facing the issue of the text overlay.
I am getting a video signal from a camera module (it can be LVDS , LVCMOS or BT656) to display it on a microdisplay unit for AR application , there are information texts that need to be overlayed on the video.
There are a lot of solutions in the market (Display controllers IC or video decoder IC),but i prefer to use simple low profile low power FPGA to do the text overlay.
Could you please help me how to start ?

**Comment by danchitnis** [comment]
replied in email. closing now.
